ssh_public_key="ssh-rsa something you created using ssh-keygen"
ssh_key_name="jrkey-vpn"
image="72d7acb16-3d4b-d0e5-d623-e43783a9b126"
profile="bc1-2x8"
slusername = "your IBM Cloud userid"
slapikey  = "and respective IBM CLoud API Key"